parserOptions:
  ecmaVersion: 2018
  sourceType: 'module'
env:
  es6: true
extends: 'sane-node'
rules:
  node/no-unsupported-features/es-syntax: 0
  no-process-exit: 0
overrides:
- files: 'test/fixtures/client-error.js'
  rules:
    node/no-missing-import: 0
