environment:
  matrix:
    - nodejs_version: "14"

  DEBUG: "fastboot-pool,flatten"

branches:
  only:
    - master

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - appveyor-retry yarn

# Post-install test scripts.
test_script:
  - yarn test

# http://help.appveyor.com/discussions/questions/1310-delete-cache
cache:
  - '%LOCALAPPDATA%\Yarn'

# Don't actually build.
build: off
